### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by MasterDrake** [estraier/tkrzw#25]
Hi, I wanted to try this library but I keep failing the compile step
I tried with x86 and x64 version of the native cmd but nothing, I keep getting compiler errors
Even though I have visual studio 2019 and I fixed the paths 
I see no issues here on github so I feel bad at asking this, since no one has a problem

![image](https://user-images.githubusercontent.com/51087997/140168328-90e6ffec-1e11-424c-8687-ed3e188c7c26.png)

Thanks and sorry to bother you

**Comment by estraier** [comment]
Just in caes, confirm this path setting in VCMakefile.

VCPATH = C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910

The latest Visual Studio I've checked just now has "14.29.30133" directory.
Without setting this properly, probably "cannot find libcpmt.lib" error would happen.

However, you errors seem different from it.
Because the first error is about linking, the compilation stage has passed.
Therefore, I suspect inconsistency of the underlying libraries to link.
Do you have multiple versions of Visual Studio on your system?

**Comment by MasterDrake** [comment]
Thanks for your response

I retried this morning and despite I haven't done something different from yesterday, now it works, I compiled, linked and the code works. Maybe it was Visual studio open...
Sorry to bother you!
