### ISSUE TITLE
Maximum HashDBM database size

### ISSUE THREAD

**Issue by svenha** [estraier/tkrzw#28]
I am considering to port a lot of code from tchdb (tokyocabinet) to Tkrzw. I thought that HashDBM would be the natural candidate, but the default maximum database size is 32 GB, while I need 0.5 to 2 TB (without compression because currently I rely on transparent filesystem compression). If HashDBM is the right choice for my porting, which choices of offset width and alignment power are recommended and how should these be applied?

BTW: I am so happy that a successor of the excellent tokyocabinet is there and maintained! Thanks a million.

**Comment by estraier** [comment]
As you say, HashDBM is suitable for your purpose.
Tuning "align_pow" or "offset_width" can increase the maximum file size.
See these examples:
C++: https://github.com/estraier/tkrzw/blob/master/example/hashdbm_ex2.cc
C: https://github.com/estraier/tkrzw/blob/master/example/langc_ex1.c

By default the align_pow is 3, which means that the start offset of every
record is aligned to 2^3=8.
32-bit address means 4GB limit.  8 * 4GB is 32GB.
If you set the align_pow to 9, the alignment becomes 2^9=512.  512 * 4GB =
2TB.
However, there's a side effect.  Records smaller than 512B take 512B.
So, if you has a lot of smaller records, increasing the alignment
deteriorates space efficiency.

Another solution is to increase the address width.  By default, the
offset_width is 4, which means 32-bit addressing.
You can set it to 5, which means 40-bit addressing whose maximum size is
1TB.
If the offset_width is 5 and the alignment_pow is 3, the maximum size is
8TB.
The side effect of increasing the offset_width is that the footprint of the
hash table and each record increases 1 byte for each record, approximately.

In sort, if most of your records are larger than 512B, you should modify
the alignment_pow.
Otherwise, you should modify the offset_width.

**Comment by svenha** [comment]
Thanks for the explanation. (The mentioned C example does not contain such tuning, yet, but I get the idea from the C++ one.)
